### PR TITLE
[Do not merge] Testing CI failure

### PR DESCRIPTION
**Pull request by atbagga**

### CODE REVIEW

**Comment by jiasli** [comment]
@haroldrandom, PR #171 is also failing with the same error:

```
py36 run-test: commands[3] | pytest
Traceback (most recent call last):
  File "/home/travis/build/microsoft/knack/.tox/py36/bin/pytest", line 7, in <module>
    from pytest import main
  File "/home/travis/build/microsoft/knack/.tox/py36/lib/python3.6/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/travis/build/microsoft/knack/.tox/py36/lib/python3.6/site-packages/_pytest/fixtures.py", line 839, in <module>
    class FixtureFunctionMarker(object):
  File "/home/travis/build/microsoft/knack/.tox/py36/lib/python3.6/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
ERROR: InvocationError for command /home/travis/build/microsoft/knack/.tox/py36/bin/pytest (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed
The command "tox" exited with 1.
```

Seems to be related to https://stackoverflow.com/a/58189684/2199657

**Comment by haroldrandom** [comment]
CI seems broken. We are fixing it.

**Comment by atbagga** [comment]
Feel free to close this PR. 
I am not closing just in case you are tracking CI failure by this.

**Comment by haroldrandom** [comment]
Close as fix here https://github.com/microsoft/knack/pull/172

**Pull request closed without merging**
